#!/usr/bin/env python3
"""Emit store-site/site.js from i18n/*.json (EN is master; others overlay)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
I18N_DIR = ROOT / "i18n"
LOCALES = [
    "en",
    "zh-Hans",
    "zh-Hant",
    "ja",
    "ko",
    "es",
    "fr",
    "de",
    "pt-BR",
    "ru",
    "ar",
    "hi",
    "id",
]
LANG_NAMES = {
    "en": "English",
    "zh-Hans": "简体中文",
    "zh-Hant": "繁體中文",
    "ja": "日本語",
    "ko": "한국어",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
    "pt-BR": "Português (Brasil)",
    "ru": "Русский",
    "ar": "العربية",
    "hi": "हिन्दी",
    "id": "Bahasa Indonesia",
}


def load_json(code: str) -> dict[str, str]:
    path = I18N_DIR / f"{code}.json"
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"{path} is not an object")
    return {str(k): str(v) for k, v in data.items() if v is not None and str(v) != ""}


def table(en: dict[str, str], code: str) -> dict[str, str]:
    data = dict(en)
    data.update(load_json(code))
    return data


def js_str(value: str) -> str:
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def emit_map(mapping, indent=2) -> str:
    pad = " " * indent
    lines = ["{"]
    items = list(mapping.items())
    for i, (key, val) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        if isinstance(val, dict):
            lines.append(f"{pad}{js_str(key)}: {emit_map(val, indent + 2)}{comma}")
        else:
            lines.append(f"{pad}{js_str(key)}: {js_str(val)}{comma}")
    lines.append((" " * (indent - 2)) + "}")
    return "\n".join(lines)


def main() -> None:
    en = load_json("en")
    if not en:
        raise SystemExit("missing i18n/en.json")
    zh = load_json("zh-Hans")
    missing_zh = [k for k in en if k not in zh]
    if missing_zh:
        raise SystemExit("zh-Hans missing " + ", ".join(missing_zh[:20]))

    i18n = {code: table(en, code) for code in LOCALES}
    locales = "[" + ", ".join(js_str(code) for code in LOCALES) + "]"
    names = emit_map(LANG_NAMES)
    payload = emit_map(i18n)
    js = f"""/* generated by build-i18n.py — do not edit by hand */
var LOCALES = {locales};
var LANG_NAMES = {names};
var I18N = {payload};

function resolveSiteLocale(tag) {{
  var raw = String(tag || '').trim().replace(/_/g, '-');
  if (LOCALES.indexOf(raw) !== -1) return raw;
  var lower = raw.toLowerCase();
  if (lower === 'zh' || lower.indexOf('zh-hans') === 0 || lower.indexOf('zh-cn') === 0 || lower.indexOf('zh-sg') === 0) return 'zh-Hans';
  if (lower.indexOf('zh-hant') === 0 || lower.indexOf('zh-tw') === 0 || lower.indexOf('zh-hk') === 0 || lower.indexOf('zh-mo') === 0) return 'zh-Hant';
  if (lower.indexOf('zh') === 0) return 'zh-Hans';
  if (lower === 'pt' || lower.indexOf('pt-') === 0) return 'pt-BR';
  if (lower === 'ar' || lower.indexOf('ar-') === 0) return 'ar';
  var lang = lower.split('-')[0];
  for (var i = 0; i < LOCALES.length; i++) {{
    var code = LOCALES[i];
    if (code.toLowerCase() === lang || code.toLowerCase().indexOf(lang + '-') === 0) return code;
  }}
  return 'en';
}}

function htmlLang(code) {{
  if (code === 'zh-Hans') return 'zh-CN';
  if (code === 'zh-Hant') return 'zh-TW';
  return code;
}}

function t(key, code) {{
  var table = I18N[code] || I18N.en;
  return table[key] || I18N.en[key] || key;
}}

function pageKey() {{
  return (document.body && document.body.getAttribute('data-page')) || 'home';
}}

function setMeta(name, value, attr) {{
  if (!value) return;
  var sel = attr === 'property' ? 'meta[property=\"' + name + '\"]' : 'meta[name=\"' + name + '\"]';
  var el = document.querySelector(sel);
  if (el) el.setAttribute('content', value);
}}

function apply(code) {{
  var resolved = resolveSiteLocale(code);
  document.documentElement.lang = htmlLang(resolved);
  document.documentElement.dir = resolved === 'ar' ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-i18n]').forEach(function (el) {{
    el.textContent = t(el.getAttribute('data-i18n'), resolved);
  }});
  document.querySelectorAll('[data-i18n-alt]').forEach(function (el) {{
    el.setAttribute('alt', t(el.getAttribute('data-i18n-alt'), resolved));
  }});
  var title = t('meta.' + pageKey() + 'Title', resolved);
  if (title && title.indexOf('meta.') !== 0) document.title = title;
  var desc = t('meta.' + pageKey() + 'Desc', resolved);
  if (desc && desc.indexOf('meta.') !== 0) {{
    setMeta('description', desc, 'name');
    setMeta('og:description', desc, 'property');
    setMeta('twitter:description', desc, 'name');
  }}
  if (title && title.indexOf('meta.') !== 0) {{
    setMeta('og:title', title, 'property');
    setMeta('twitter:title', title, 'name');
  }}
  var ogLocale = resolved === 'zh-Hans' ? 'zh_CN' : (resolved === 'zh-Hant' ? 'zh_TW' : resolved.replace('-', '_'));
  setMeta('og:locale', ogLocale, 'property');
  var sel = document.getElementById('site-lang');
  if (sel) sel.value = resolved;
  try {{ localStorage.setItem('jn-lang', resolved); }} catch (e) {{}}
  try {{
    var url = new URL(window.location.href);
    if (url.searchParams.get('lang') !== resolved) {{
      url.searchParams.set('lang', resolved);
      history.replaceState(null, '', url.pathname + url.search + url.hash);
    }}
  }} catch (e) {{}}
}}

function fillLangSelect() {{
  var sel = document.getElementById('site-lang');
  if (!sel) return;
  sel.innerHTML = '';
  LOCALES.forEach(function (code) {{
    var opt = document.createElement('option');
    opt.value = code;
    opt.textContent = LANG_NAMES[code] || code;
    sel.appendChild(opt);
  }});
  sel.addEventListener('change', function () {{ apply(sel.value); }});
}}

(function boot() {{
  fillLangSelect();
  var stored = '';
  try {{ stored = localStorage.getItem('jn-lang') || ''; }} catch (e) {{}}
  var fromQuery = '';
  try {{ fromQuery = new URL(window.location.href).searchParams.get('lang') || ''; }} catch (e) {{}}
  apply(fromQuery || stored || navigator.language || 'zh-Hans');
}})();
"""
    (ROOT / "site.js").write_text(js, encoding="utf-8")
    print("wrote site.js", len(en), "keys", len(LOCALES), "locales")


if __name__ == "__main__":
    main()
